In [18]:
# задание 1

In [4]:
import numpy as np

In [5]:
Z = np.arange(5)
Z = Z[::-1]
Z

array([4, 3, 2, 1, 0])

In [6]:
# задание 2

In [7]:
a = np.diag(np.arange(7), k=0)
a
a.sum()

21

In [8]:
print(a)

[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 5 0]
 [0 0 0 0 0 0 6]]


In [ ]:
# задание 5

In [ ]:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [19]:
a=np.array(
[
    [4, 2, 1], 
    [1, 3, 0], 
    [0, 5, 4]
])

In [20]:
b=np.array(
[
    [4],
    [12],
    [-3]
])

In [21]:
from numpy import linalg

In [22]:
linalg.solve(a,b)

array([[ 0.46666667],
       [ 3.84444444],
       [-5.55555556]])

In [ ]:
# задание 3

In [2]:
import pandas as pd

In [24]:
data=pd.read_csv('C:\\data\\ratings.csv')

In [25]:
data.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [26]:
len(data)

100836

In [45]:
best_films = data[data.rating==5.0]
best_films.head()

userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [48]:
best_films['movieId'].value_counts(normalize=True)
# ОТВЕТ: фильму с id 318 было выставлено больше всего оценок 5.0

318       0.011581
296       0.009310
356       0.008781
2571      0.008251
260       0.007872
593       0.006964
527       0.006964
858       0.006661
2959      0.006131
1196      0.006056
110       0.006056
50        0.005374
1198      0.005223
1210      0.004920
2858      0.004920
589       0.004844
4993      0.004693
2028      0.004617
608       0.004315
1197      0.004163
7153      0.004012
47        0.003936
1136      0.003860
5952      0.003709
58559     0.003709
1270      0.003709
1221      0.003633
1         0.003558
541       0.003482
457       0.003482
            ...   
550       0.000076
6944      0.000076
6952      0.000076
2690      0.000076
619       0.000076
467       0.000076
2594      0.000076
94677     0.000076
2522      0.000076
86668     0.000076
49651     0.000076
6773      0.000076
6664      0.000076
4617      0.000076
6765      0.000076
100882    0.000076
531       0.000076
172583    0.000076
4713      0.000076
4649      0.000076
100906    0.000076
8810      0.

In [ ]:
# задание 4

In [62]:
data_2=pd.read_csv('C:\\data\\power_1.csv')

In [64]:
data_2.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [99]:
filtered_countries = data_2[ (data_2['country']=='Estonia') | (data_2['country']=='Lithuania') | (data_2['country']=='Latvia')]

filtered_countries.head()

country  year  quantity  category
373  Lithuania  2014      39.0         1
374  Lithuania  2013     192.0         1
375  Lithuania  2012     196.0         1
376  Lithuania  2011     171.0         1
377  Lithuania  2010     158.0         1

In [100]:
filtered_countries['country'].unique()

array(['Lithuania', 'Latvia', 'Estonia'], dtype=object)

In [109]:
filtered_categories = filtered_countries[ (filtered_countries['category']==4) | (filtered_countries['category']==12) | (filtered_countries['category']==21)]
filtered_categories.head()

country  year  quantity  category
10617  Estonia  2008       1.0         4
10618  Estonia  2007       0.0         4
10619  Estonia  2006       0.0         4
10620  Estonia  2005       1.0         4
10621  Estonia  2004       1.0         4

In [110]:
filtered_categories['category'].unique()

array([ 4, 12, 21], dtype=int64)

In [114]:
filtered_by_year = filtered_categories[ (filtered_categories['year']==2005) | (filtered_categories['year']==2006) | (filtered_categories['year']==2007) | (filtered_categories['year']==2008) | (filtered_categories['year']==2009) | (filtered_categories['year']==2010)]

In [116]:
print(filtered_by_year.groupby(['country'])['category'].count())

country
Estonia       99
Latvia        92
Lithuania    220
Name: category, dtype: int64
